import { readdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { defineConfig, type Plugin } from "vite";
import dts from "vite-plugin-dts";

const isDocsRoot = process.argv.some(
  (arg) => arg.replaceAll("\\", "/").endsWith("/docs") || arg === "docs",
);

const elementsDir = resolve(__dirname, "src/elements");

/**
 * Leaflet and its markercluster plugin are peer dependencies — they are
 * dynamically imported by `cui-map` only, and kept external so consumers
 * provide (and dedupe) their own copy. The `?inline` CSS imports use distinct
 * specifiers and stay bundled.
 */
const externalDeps = (id: string): boolean =>
  id === "leaflet" || id === "leaflet.markercluster";

/**
 * Per-component self-registering entries (`src/elements/*.ts`, generated by
 * `scripts/build-elements.mjs`). Built in a second pass so the standalone
 * `combat-ui.js` bundle stays a single file while consumers can also import
 * just the components they use.
 */
function elementEntries(): Record<string, string> {
  return Object.fromEntries(
    readdirSync(elementsDir)
      .filter((file) => file.endsWith(".ts"))
      .map((file) => [file.slice(0, -3), resolve(elementsDir, file)]),
  );
}

const docsDir = resolve(__dirname, "docs");
const docsPages = [
  "atoms",
  "carousel",
  "components",
  "forms",
  "foundations",
  "index",
  "layouts",
  "map",
  "motion",
  "navigation",
  "overlays",
  "roadmap",
  "sections",
  "theming",
];

function docsIncludes(): Plugin {
  const partialsDir = resolve(docsDir, "_partials");
  return {
    name: "docs-includes",
    transformIndexHtml(html, ctx) {
      return html.replace(
        /<!--#include\s+(\S+?)(?:\?([^>]+?))?\s*-->/g,
        (_, path, query) => {
          const fullPath = resolve(dirname(ctx.filename), path);
          let partial = readFileSync(fullPath, "utf-8");
          if (query) {
            const params = new URLSearchParams(query);
            const current = params.get("current");
            if (current) {
              partial = partial.replace(
                new RegExp(`(<a[^>]*\\sdata-page="${current}")`),
                `$1 aria-current="page"`,
              );
            }
          }
          return partial;
        },
      );
    },
    configureServer(server) {
      server.watcher.add(partialsDir);
      server.watcher.on("change", (file) => {
        if (file.replaceAll("\\", "/").includes("/docs/_partials/")) {
          server.ws.send({ type: "full-reload" });
        }
      });
    },
  };
}

export default defineConfig(({ mode }) => {
  if (isDocsRoot) {
    return {
      base: "./",
      plugins: [docsIncludes()],
      build: {
        target: "baseline-widely-available",
        sourcemap: true,
        rollupOptions: {
          input: Object.fromEntries(
            docsPages.map((name) => [name, resolve(docsDir, `${name}.html`)]),
          ),
        },
      },
    };
  }

  // Second pass: one self-contained file per component. Does not empty the
  // dist dir (it shares it with the standalone bundle) and skips dts — the
  // per-element declarations come from `tsc -b` (the `typecheck` step).
  if (mode === "elements") {
    return {
      base: "/",
      build: {
        target: "baseline-widely-available",
        sourcemap: false,
        emptyOutDir: false,
        lib: {
          entry: elementEntries(),
          formats: ["es"],
          fileName: (_format, name) => `${name}.js`,
        },
        rollupOptions: {
          external: externalDeps,
          output: {
            preserveModules: false,
          },
        },
      },
    };
  }

  // Default pass: the tree-shakeable root (`combat-ui.js`, from src/index.ts)
  // plus the batteries-included `auto.js` (registers every element + ships the
  // global stylesheet).
  return {
    base: "/",
    plugins: [
      dts({
        tsconfigPath: "./tsconfig.src.json",
        outDirs: "dist/types",
        insertTypesEntry: true,
      }),
    ],
    build: {
      target: "baseline-widely-available",
      sourcemap: false,
      lib: {
        entry: {
          "combat-ui": resolve(__dirname, "src/index.ts"),
          auto: resolve(__dirname, "src/auto.ts"),
        },
        formats: ["es"],
        fileName: (_format, name) => `${name}.js`,
        cssFileName: "combat-ui",
      },
      rollupOptions: {
        external: externalDeps,
        output: {
          preserveModules: false,
          chunkFileNames: "combat-ui-core-[hash].js",
        },
      },
    },
  };
});
